import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import type { Transaction } from "../types";
import { CategoryIcon } from "./CategoryIcon";

const money = (value: number | string) => Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export function RecentTransactions({ transactions, loading }: { transactions: Transaction[]; loading: boolean }) {
  if (loading) return <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="h-6 w-44 animate-pulse rounded bg-slate-100" /><div className="mt-6 h-32 animate-pulse rounded-2xl bg-slate-50" /></section>;
  return <section className="rounded-3xl border border-transparent bg-white p-6 transition-all duration-200 ease-in-out hover:-translate-y-0.5 hover:border-slate-200 hover:shadow-xl"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Atividade</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Transações recentes</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">Últimos lançamentos</span></div>{transactions.length === 0 ? <div className="mt-8 rounded-2xl bg-slate-50 px-5 py-10 text-center text-sm text-slate-500">Ainda não há transações. Seu próximo lançamento aparecerá aqui.</div> : <div className="mt-5 divide-y divide-slate-100">{transactions.map(transaction => <article key={transaction.id} className="flex items-center gap-3 py-4 first:pt-1"><span className="grid size-11 shrink-0 place-items-center rounded-2xl" style={{ backgroundColor: `${transaction.category.color}22`, color: transaction.category.color }}><CategoryIcon icon={transaction.category.icon} /></span><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-800">{transaction.description}</p><p className="mt-0.5 text-sm text-slate-500">{transaction.category.name} · {transaction.paymentMethod === "CREDIT_CARD" ? "Cartão" : "Conta"}</p></div><div className={`flex shrink-0 items-center gap-1 font-semibold ${transaction.type === "INCOME" ? "text-emerald-600" : "text-rose-600"}`}>{transaction.type === "INCOME" ? <ArrowUpRight size={17} /> : <ArrowDownRight size={17} />}{money(transaction.value)}</div></article>)}</div>}</section>;
}
